### ISSUE TITLE
[FR] Automatic Probing

### ISSUE THREAD

**Issue by Stinosko** [Willmac16/OctoPrint-GcodeLeveling#1]
It would be nice if this plugin could have a option to read and use a Laser Distance Sensor. So it can automatically calculate the angle of the surface when you attach such a sensor to the printing head 🙂

**Comment by Willmac16** [comment]
Very interesting! Do you have any idea of the specifics: what laser sensor you would use, how you would have it connected and set up (probably to a raspberry pi for it to make sense with this plugin), and what machine you would be using it on?

**Comment by Willmac16** [comment]
@Stinosko do you have a specific laser distance sensor in mind?

**Comment by Roukie686868** [comment]
Indeed an interesting idea if this is accurate to less than 1mm. For my CNC I have to set up a matrix and than by hand go to each coordinate at the coordinate use the G38.2 S0 command to probe the bed height. Then with M114 read out the height, record it on paper and move to the next point to repeat the whole process over and over.
The ability to list the coordinates up front and have the machine go there fully automatic and laser would be fantastic. In my case just go to the point and ask to probe and ready the Z value from M114 would really speed things up.

By the way impressive programming.

**Comment by Willmac16** [comment]
@Roukie686868 I am actively working on auto-probing with `G38.2` and a physical probe recognized by the machine's firmware. I'll let you know when I have something you could test.

@Stinosko I am interested in implementing a laser probing system, but without specifics, it is hard to make anything compatible with people's setups.

**Comment by Roukie686868** [comment]
Looking forward to that. Thanks for the update

**Comment by Willmac16** [comment]
@Roukie686868 you can test the changes by installing with `https://github.com/Willmac16/OctoPrint-GcodeLeveling/archive/devel.zip`

**Comment by Willmac16** [comment]
I looks like the current version may have some issue actually saving the points (it gathers them fine), so I will get back to you once I fix that.

**Comment by Willmac16** [comment]
@Roukie686868 It should be working now.

**Comment by Stinosko** [comment]
@Willmac16 I totally forgot to answer you: 

I don't have a laser sensor yet but my machine is the creality CP-01 3 in 1. It was just a idea to use a laser through the GPIO pins of the raspberry pi to calculate the angle of the bed instead of doing it manually. You place the print head at a save distance for example at 10mm height with the laser distance measure sensor on it. Scan the surface area on multiple locations and calculate the angle of the bed automatically.

**Comment by Willmac16** [comment]
@Stinosko the main problem with a laser is going to be physical accuracy; most hobby electronics lasers are at best accurate to a millimeter, while a cnc machine/3d printer should be functional to a fraction of a millimeter. 

If you do get a touch sensor working with your firmware, then installing from the link above would let you have the plugin auto-probe a grid for its use.

**Comment by Stinosko** [comment]
@Willmac16 You're right, a touch sensor it a much better solution! I give it a look when i have time 🙂

**Comment by Willmac16** [comment]
Added in with 0.4.0
