### ISSUE TITLE
Python 2 issue with 0.3

### ISSUE THREAD

**Issue by dant220** [Willmac16/OctoPrint-GcodeLeveling#11]
When I try to install it seems successful. Numpy is installed. And I never see it in the UI. When I look under installed plugins and search for "gcode" I do not see it listed. I tried several times and rebooted to be sure. Please find attached the install log. 

Thank you in advance for any help. 

[OctoprintIntall.txt](https://github.com/Willmac16/OctoPrint-GcodeLeveling/files/5954644/OctoprintIntall.txt)

**Comment by Willmac16** [comment]
@dant220 could you send your octoprint.log file

**Comment by Willmac16** [comment]
I suspect either there is an error that python is throwing when it parses the plugin's code (more likely, especially if it is a python2 issue) or somehow you installed it on a different version of python than you are currently running octoprint off of (less likely).

**Comment by Willmac16** [comment]
okay I found the python 2 error, I will patch accordingly

**Comment by Willmac16** [comment]
0.3.2 should fix it, you may need to force the update cache to refresh(in software update > advanced) if you want the update before octoprint checks on its own.

**Comment by dant220** [comment]
I will check it ASAP and report back. Thank you so much!

**Comment by dant220** [comment]
It is working now. My octoprint is using 2.7. Thank you so much.
