### ISSUE TITLE
Install fails on OctoPrint

### ISSUE THREAD

**Issue by CmdrCody51** [Willmac16/OctoPrint-GcodeLeveling#2]
This is a manually installed OctoPrint on top of a full Buster install.
OctoPrint (NOT OctoPi) need to add "sudo apt install libatlas3-base" (included in OctoPi).
I don't know how you do that but cp2004 said it was noted in BedLevelVisualizer that this is required.
After installing the lib file - the install ran flawlessly.

**Comment by Willmac16** [comment]
Thank you for letting me know! I added a note to the plugins.octoprint.org page and the repo's readme. Let me know how the plugin works for you.
